app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("image-speak/", include("image_speech.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_speech/urls.py
from django.urls import path

from .views import *

app_name = "image_speech"
urlpatterns = [
    path("", index, name="index"),
    path("new/", create, name="create"),
    path("generate/", generate, name="generate"),
    path("<uuid:uuid>/", detail, name="detail"),
    path("<uuid:uuid>/regenerate", regenerate, name="regenerate"),
]

image_speech/models.py
import uuid

from django.db import models

from . import filepaths as fp


class Image(models.Model):
    uuid = models.UUIDField(
        unique=True,
        editable=False,
        default=uuid.uuid4,
    )
    image_url = models.URLField(
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )


class Speech(models.Model):
    image = models.ForeignKey(
        Image,
        on_delete=models.CASCADE,
    )
    uuid = models.UUIDField(
        unique=True,
        editable=False,
        default=uuid.uuid4,
    )
    transcript = models.TextField()
    audio_file = models.FileField(upload_to=fp.audio_path, null=True, blank=True)
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "index.html")

image_speech/views.py
from django.contrib import messages
from django.core.files.base import ContentFile
from django.shortcuts import redirect, render
from django.urls import reverse
from openai import APIConnectionError, APIError, OpenAI, RateLimitError

from .models import Image, Speech


def index(request):
    images = Image.objects.all()
    context = {
        "images": images,
    }
    return render(request, "image_speech/index.html", context)


def create(request):
    return render(request, "image_speech/create.html")


def generate(request):
    if request.method == "POST":
        image_url = request.POST.get("image_url", None)
        voice = request.POST.get("voice", "alloy")
        fail_url = reverse("image_speech:create")
        print(image_url)
        if image_url is None:
            return redirect(fail_url)

        client = OpenAI()
        try:
            # Image to Text
            vision = client.chat.completions.create(
                model="gpt-4-vision-preview",
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": "If there are any readable text found inside the image, extract the information and return only a short transcript containing the important details. If not, provide a short description for the image. No need to notify about missing text. Present it in a way that is to be delivered in speech for people with visual difficulties.",
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": image_url,
                                },
                            },
                        ],
                    }
                ],
                max_tokens=1000,
            )
            transcript = vision.choices[0].message.content
            image = Image.objects.create(image_url=image_url)

            # Text to Speech
            speech = Speech(image=image, transcript=transcript)
            audio = client.audio.speech.create(
                model="tts-1",
                voice=voice,
                input=transcript,
                response_format="mp3",
            )
            speech.audio_file.save(f"{speech.uuid}.mp3", ContentFile(audio.content))
            speech.save()

            messages.success(request, "Sample successfully generated")
            success_url = reverse("image_speech:detail", kwargs={"uuid": image.uuid})
            return redirect(success_url)

        except APIConnectionError as e:
            messages.error(request, "Failed to connect to OpenAI API")
        except RateLimitError as e:
            messages.error(request, "OpenAI API request exceeded rate limit")
        except APIError as e:
            messages.error(request, "OpenAI API returned an API Error")
    return redirect(fail_url)


def detail(request, uuid=None):
    image = Image.objects.get(uuid=uuid)
    speeches = image.speech_set.order_by("-created_at").all()
    context = {
        "image": image,
        "speeches": speeches,
    }

    return render(request, "image_speech/detail.html", context)


def regenerate(request, uuid=None):
    if request.method == "POST":
        image = Image.objects.get(uuid=uuid)
        voice = request.POST.get("voice", "alloy")
        client = OpenAI()
        try:
            # Image to Text
            vision = client.chat.completions.create(
                model="gpt-4-vision-preview",
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": "If there are any readable text found inside the image, extract the information and return only a short transcript containing the important details. If not, provide a short description for the image. No need to notify about missing text. Present it in a way that is to be delivered in speech for people with visual difficulties.",
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": image.image_url,
                                },
                            },
                        ],
                    }
                ],
                max_tokens=1000,
            )
            transcript = vision.choices[0].message.content

            # Text to Speech
            speech = Speech(image=image, transcript=transcript)
            audio = client.audio.speech.create(
                model="tts-1",
                voice=voice,
                input=transcript,
                response_format="mp3",
            )
            speech.audio_file.save(f"{speech.uuid}.mp3", ContentFile(audio.content))
            speech.save()
            messages.success(request, "Sample successfully generated")
            success_url = reverse("image_speech:detail", kwargs={"uuid": image.uuid})
            return redirect(success_url)

        except APIConnectionError as e:
            messages.error(request, "Failed to connect to OpenAI API")
        except RateLimitError as e:
            messages.error(request, "OpenAI API request exceeded rate limit")
        except APIError as e:
            messages.error(request, "OpenAI API returned an API Error")

        success_url = reverse("image_speech:detail", kwargs={"uuid": image.uuid})
        return redirect(success_url)
    fail_url = reverse("image_speech:detail", kwargs={"uuid": image.uuid})
    return redirect(fail_url)

templates/_base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Micro-SaaS - ImageSpeak</title>

  {% compress css %}
  <link rel="stylesheet" href="{% static 'src/output.css' %}">
  {% endcompress %}

</head>

<body class="bg-slate-100">
  {% include "_messages.html" %}

  <nav class=" bg-white border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <a href="{% url 'image_speech:index' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
        <svg class="w-[30px] h-[30px] text-gray-800 dark:text-white" aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg" fill="#1d4ed8" viewBox="0 0 18 18">
          <path
            d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
        </svg>
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Micro-SaaS</span>
      </a>
      <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
        <a href="{% url 'image_speech:create' %}"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Get
          started</a>
        <button data-collapse-toggle="navbar-cta" type="button"
          class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
          aria-controls="navbar-cta" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M1 1h15M1 7h15M1 13h15" />
          </svg>
        </button>
      </div>
      <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
        <ul
          class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <a href="{% url 'image_speech:index' %}"
              class="block py-2 px-3 md:p-0 text-gray-900 rounded font-bold text-xl hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">ImageSpeak</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="max-w-screen-xl mx-auto mt-12">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
</body>

</html>

templates/image_speech/create.html
{% extends "_base.html" %}

{% block content %}
<form class=" mx-auto gap-8  p-4" action="{% url 'image_speech:generate' %}" method="post">
  {% csrf_token %}
  <div class="mb-5">
    <label for="image_url" class="block mb-2 font-medium text-gray-900 dark:text-white">Image
      URL</label>
    <input type="url" id="image_url" name="image_url" aria-describedby="helper-text-explanation" required
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      placeholder="Enter image url here">

    <p id="helper-text-explanation" class="mt-2 text-sm text-gray-500 dark:text-gray-400">Enter an image url to
      generate
      an audio file with.
    </p>
  </div>
  <div class="mb-5">
    <h3 class="mb-2 font-medium text-gray-900 dark:text-white">Select Voice</h3>
    <p id="helper-text-explanation" class="mt-2 text-sm text-gray-500 dark:text-gray-400">Select voice to be used in
      the audio file.
    </p>
    <ul class="grid w-full md:grid-cols-2 gap-2 mt-4">
      <li>
        <input type="radio" id="alloy" name="voice" value="alloy" class="hidden peer" required>
        <label for="alloy"
          class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="w-full text-lg font-semibold">Alloy</div>
          <audio src="https://cdn.openai.com/API/docs/audio/alloy.wav"
            class="w-full border-8 border-slate-400 rounded-full" controls></audio>
        </label>
      </li>
      <li>
        <input type="radio" id="echo" name="voice" value="echo" class="hidden peer" required>
        <label for="echo"
          class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="w-full text-lg font-semibold">Echo</div>
          <audio src="https://cdn.openai.com/API/docs/audio/echo.wav"
            class="w-full border-8 border-slate-400 rounded-full" controls></audio>
        </label>
      </li>
      <li>
        <input type="radio" id="fable" name="voice" value="fable" class="hidden peer" required>
        <label for="fable"
          class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="w-full text-lg font-semibold">Fable</div>
          <audio src="https://cdn.openai.com/API/docs/audio/fable.wav"
            class="w-full border-8 border-slate-400 rounded-full" controls></audio>
        </label>
      </li>
      <li>
        <input type="radio" id="onyx" name="voice" value="onyx" class="hidden peer" required>
        <label for="onyx"
          class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="w-full text-lg font-semibold">Onyx</div>
          <audio src="https://cdn.openai.com/API/docs/audio/onyx.wav"
            class="w-full border-8 border-slate-400 rounded-full" controls></audio>
        </label>
      </li>
      <li>
        <input type="radio" id="nova" name="voice" value="nova" class="hidden peer" required>
        <label for="nova"
          class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="w-full text-lg font-semibold">Nova</div>
          <audio src="https://cdn.openai.com/API/docs/audio/nova.wav"
            class="w-full border-8 border-slate-400 rounded-full" controls></audio>
        </label>
      </li>
      <li>
        <input type="radio" id="shimmer" name="voice" value="shimmer" class="hidden peer" required>
        <label for="shimmer"
          class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
          <div class="w-full text-lg font-semibold">Shimmer</div>
          <audio src="https://cdn.openai.com/API/docs/audio/shimmer.wav"
            class="w-full border-8 border-slate-400 rounded-full" controls></audio>
        </label>
      </li>
    </ul>
  </div>
  <button type="submit"
    class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Generate</button>
</form>

{% endblock content %}

templates/image_speech/detail.html
{% extends "_base.html" %}
{% load static %}

{% block content%}
<section class="dark:bg-gray-900 p-4">
  <div class="grid md:grid-cols-2 gap-8">
    <img class="h-auto max-w-full object-cover rounded-lg shadow-xl dark:shadow-gray-800" src="{{ image.image_url }}"
      alt="Uploaded image">

    <div id="controls-carousel" class="relative w-full h-screen" data-carousel="static">
      <!-- Carousel wrapper -->
      <div class="relative overflow-hidden h-screen rounded-lg">
        {% for speech in speeches %}
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
          <audio controls class="w-full border-8 border-slate-400 rounded-full">
            <source src="{{ speech.audio_file.url }}" type="audio/mp3">
            Browser does not support the audio format
          </audio>
          <h1 class="text-2xl font-bold dark:text-white mt-6 text-center">Transcript</h1>
          <div class="mt-4 p-4 w-full">
            <p class="whitespace-pre-wrap">{{ speech.transcript }}</p>
          </div>
        </div>
        {% endfor %}

        <!-- Regenerate -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
          <form action="{% url 'image_speech:regenerate' image.uuid %}" method="post" class="p-8">
            {% csrf_token %}
            <h1 class="text-2xl font-bold dark:text-white mt-14 text-center">Hmmm...</h1>
            <p class="mt-4 text-center">Not feeling the results? No worries!
            </p>
            <div class="mb-5">
              <h3 class="mb-2 font-medium text-gray-900 dark:text-white">Select Voice</h3>
              <p id="helper-text-explanation" class="mt-2 text-sm text-gray-500 dark:text-gray-400">Select voice to be
                used in
                the audio file.
              </p>
              <ul class="grid w-full md:grid-cols-2 gap-2 mt-4">
                <li>
                  <input type="radio" id="alloy" name="voice" value="alloy" class="hidden peer" required>
                  <label for="alloy"
                    class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <div class="w-full text-lg font-semibold">Alloy</div>
                    <audio src="https://cdn.openai.com/API/docs/audio/alloy.wav"
                      class="w-full border-8 border-slate-400 rounded-full" controls></audio>
                  </label>
                </li>
                <li>
                  <input type="radio" id="echo" name="voice" value="echo" class="hidden peer" required>
                  <label for="echo"
                    class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <div class="w-full text-lg font-semibold">Echo</div>
                    <audio src="https://cdn.openai.com/API/docs/audio/echo.wav"
                      class="w-full border-8 border-slate-400 rounded-full" controls></audio>
                  </label>
                </li>
                <li>
                  <input type="radio" id="fable" name="voice" value="fable" class="hidden peer" required>
                  <label for="fable"
                    class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <div class="w-full text-lg font-semibold">Fable</div>
                    <audio src="https://cdn.openai.com/API/docs/audio/fable.wav"
                      class="w-full border-8 border-slate-400 rounded-full" controls></audio>
                  </label>
                </li>
                <li>
                  <input type="radio" id="onyx" name="voice" value="onyx" class="hidden peer" required>
                  <label for="onyx"
                    class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <div class="w-full text-lg font-semibold">Onyx</div>
                    <audio src="https://cdn.openai.com/API/docs/audio/onyx.wav"
                      class="w-full border-8 border-slate-400 rounded-full" controls></audio>
                  </label>
                </li>
                <li>
                  <input type="radio" id="nova" name="voice" value="nova" class="hidden peer" required>
                  <label for="nova"
                    class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <div class="w-full text-lg font-semibold">Nova</div>
                    <audio src="https://cdn.openai.com/API/docs/audio/nova.wav"
                      class="w-full border-8 border-slate-400 rounded-full" controls></audio>
                  </label>
                </li>
                <li>
                  <input type="radio" id="shimmer" name="voice" value="shimmer" class="hidden peer" required>
                  <label for="shimmer"
                    class="inline-flex items-center justify-between w-full py-1 px-4 text-gray-500 bg-white border border-gray-200 rounded-lg cursor-pointer dark:hover:text-gray-300 dark:border-gray-700 dark:peer-checked:text-blue-500 peer-checked:border-blue-600 peer-checked:text-blue-600 hover:text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700">
                    <div class="w-full text-lg font-semibold">Shimmer</div>
                    <audio src="https://cdn.openai.com/API/docs/audio/shimmer.wav"
                      class="w-full border-8 border-slate-400 rounded-full" controls></audio>
                  </label>
                </li>
              </ul>
            </div>
            <button type="submit"
              class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 w-full">New
              Results</button>
          </form>
        </div>
      </div>

      <!-- Slider controls -->
      <button type="button" class="absolute top-20 left-4 z-30 cursor-pointer group focus:outline-none"
        data-carousel-prev>
        <span
          class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-slate-400/30 dark:bg-gray-800/30 group-hover:bg-slate-400/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-slate-400 dark:group-focus:ring-gray-800/70 group-focus:outline-none">
          <svg class="w-4 h-4 text-slate-400 dark:text-gray-800 rtl:rotate-180" aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M5 1 1 5l4 4" />
          </svg>
          <span class="sr-only">Previous</span>
        </span>
      </button>
      <button type="button" class="absolute top-20 right-4 z-30 cursor-pointer group focus:outline-none"
        data-carousel-next>
        <span
          class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-slate-400/30 dark:bg-gray-800/30 group-hover:bg-slate-400/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-sbg-slate-400 dark:group-focus:ring-gray-800/70 group-focus:outline-none">
          <svg class="w-4 h-4 text-sbg-slate-400 dark:text-gray-800 rtl:rotate-180" aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="m1 9 4-4-4-4" />
          </svg>
          <span class="sr-only">Next</span>
        </span>
      </button>
    </div>
  </div>

</section>
{% endblock content %}

templates/index.html
{% extends "_base.html" %}

{% block content %}
<h1 class="text-3xl text-green-800">Django + Tailwind CSS + Flowbite</h1>
{% endblock content %}